on: [push]

jobs:
  lighthouse-performance-action:
    runs-on: ubuntu-latest
    name: Lighthouse Performance Action
    steps:
      - uses: actions/checkout@v2
      - name: Output lighthouse performance
        id: lighthouse
        uses: ./
        with:
          config: './github/workflows/lighthouserc.js'
      # Use the output from the `lighthouse` step
      - name: Get the output Performance
        run: |
          echo "url is ${{ steps.lighthouse.outputs.url1 }}"
          echo "performance is ${{ steps.lighthouse.outputs.url1_performance }}"
          echo "accessibility is ${{ steps.lighthouse.outputs.url1_accessibility }}"
          echo "bestPractices is ${{ steps.lighthouse.outputs.url1_bestPractices }}"
          echo "seo is ${{ steps.lighthouse.outputs.url1_seo }}"
          echo "pwa is ${{ steps.lighthouse.outputs.url1_pwa }}"
          echo "firstContentfulPaint is ${{ steps.lighthouse.outputs.url1_firstContentfulPaint }}"
          echo "speedIndex is ${{ steps.lighthouse.outputs.url1_speedIndex }}"
          echo "largestContentfulPaint is ${{ steps.lighthouse.outputs.url1_largestContentfulPaint }}"
          echo "interactive is ${{ steps.lighthouse.outputs.url1_interactive }}"
          echo "totalBlockingTime is ${{ steps.lighthouse.outputs.url1_totalBlockingTime }}"
          echo "publicUrl is ${{ steps.lighthouse.outputs.url1_publicUrl }}"
          echo "url is ${{ steps.lighthouse.outputs.url2 }}"
          echo "performance is ${{ steps.lighthouse.outputs.url2_performance }}"
          echo "accessibility is ${{ steps.lighthouse.outputs.url2_accessibility }}"
          echo "bestPractices is ${{ steps.lighthouse.outputs.url2_bestPractices }}"
          echo "seo is ${{ steps.lighthouse.outputs.url2_seo }}"
          echo "pwa is ${{ steps.lighthouse.outputs.url2_pwa }}"
          echo "firstContentfulPaint is ${{ steps.lighthouse.outputs.url2_firstContentfulPaint }}"
          echo "speedIndex is ${{ steps.lighthouse.outputs.url2_speedIndex }}"
          echo "largestContentfulPaint is ${{ steps.lighthouse.outputs.url2_largestContentfulPaint }}"
          echo "interactive is ${{ steps.lighthouse.outputs.url2_interactive }}"
          echo "totalBlockingTime is ${{ steps.lighthouse.outputs.url2_totalBlockingTime }}"
          echo "publicUrl is ${{ steps.lighthouse.outputs.url2_publicUrl }}"
